### ISSUE TITLE
R8 error

### ISSUE THREAD

**Issue by moljac** [Leozin777/NotificationError#1]
error

```
MSBUILD : java error JAVA0000: Error in /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class: [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Type androidx.collection.ArrayMapKt is defined multiple times: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/moljac/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Compilation failed [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:126) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.main(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:5) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at Version.fakeStackEntry(Version_8.1.56.java:0) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.M.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:5) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:81) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:32) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:31) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.b(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:2) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:26) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.b(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:13) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:24) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:113) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	... 1 more [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Caused by: com.android.tools.r8.utils.b: Type androidx.collection.ArrayMapKt is defined multiple times: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/moljac/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.O2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:21) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.O2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:26) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:44) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:10) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:6) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.graph.b4$a.e(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:7) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:58) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:9) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:8) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:29) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.d(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:17) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.c(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:1) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:28) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	... 6 more [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]

Build FAILED.

MSBUILD : java error JAVA0000: Error in /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class: [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Type androidx.collection.ArrayMapKt is defined multiple times: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/moljac/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Compilation failed [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:126) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.main(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:5) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at Version.fakeStackEntry(Version_8.1.56.java:0) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.M.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:5) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:81) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:32) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:31) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.b(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:2) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:26) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.b(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:13) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:24) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:113) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	... 1 more [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: Caused by: com.android.tools.r8.utils.b: Type androidx.collection.ArrayMapKt is defined multiple times: /Users/moljac/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.2/buildTransitive/net7.0-android33.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/moljac/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.O2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:21) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.O2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:26) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:44) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:10) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:6) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.graph.b4$a.e(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:7) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:58) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:9) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:8) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:29) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.d(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:17) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.D8.c(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:1) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:28) [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000: 	... 6 more [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
MSBUILD : java error JAVA0000:  [/Users/moljac/Downloads/Leozin777--NotificationError/NotificationError-main/NotificationError.csproj::TargetFramework=net8.0-android]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:48.53

```

**Comment by moljac** [comment]
workaround

add explicitly following reference:

```
	  <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.3.0.2" />	  
```

**Comment by Leozin777** [comment]
Thanks man

**Comment by moljac** [comment]
> Thanks man

You re welcome.
